In [40]:
import numpy as np
userInput = input().split(' ')

tempsc = []
sc = []
for item in userInput:
    if item == '-1':
        sc.append(tempsc)
        numGroups = int(len(tempsc)/3)
        tempsc = []
    else:
        tempsc.append(int(item))

score1 = np.array(sc[0]).reshape(numGroups, 3)
score2 = np.array(sc[1]).reshape(numGroups, 3)

div = np.full((numGroups,3), 2)

add = np.add(score1, score2)
average = np.divide(add, div)

for i in range(average.shape[0]):
    average[i][0]+=10

for i in range(numGroups):
    for j in range(3):
        if average[i][j] < 60:
            average[i][j] = -1
        
print(score1)
print(score2)
print(average)

65 70 85 90 100 70 70 50 20 -1 80 90 60 30 95 60 75 20 80 -1
[[ 65  70  85]
 [ 90 100  70]
 [ 70  50  20]]
[[80 90 60]
 [30 95 60]
 [75 20 80]]
[[82.5 80.  72.5]
 [70.  97.5 65. ]
 [82.5 -1.  -1. ]]
